- name: Configure web servers
  hosts: web
  become: true
  gather_facts: true
  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present
        update_cache: true
    - name: create directory structure for web documents
      ansible.builtin.file:
        path: /web/html
        state: directory
        owner: root
        group: root
        mode: "0755"
    - name: copy nginx conf file to server
      ansible.builtin.copy:
        src: files/nginx.conf
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: "0644"
      notify: Reload nginx
    - name: create link to nginx config file to enable it
      ansible.builtin.file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
        force: true
      notify: Reload nginx
    - name: Generate index.html file from template
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /web/html/index.html
        owner: root
        group: root
        mode: "0644"
      notify: Reload nginx
    - name: reload nginx service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
  handlers:
    - name: Reload nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
